POST https://leetcode.com/problems/concatenation-of-array/interpret_solution/ HTTP/1.1
User-Agent: curl/8.0.1
Host:leetcode.com
Accept:*/*
content-type:application/json
Origin:https://leetcode.com
Referer:https://leetcode.com/problems/concatenation-of-array/
x-csrftoken:RtRYPnzpk1VPxFNUT2q88iEs3ZyjJQFuVe5REeLGVJrKfprdE1ZJFWIFMhvDy5Af
Cookie:LEETCODE_SESSION=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNDkxMjU4NyIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImRqYW5nby5jb250cmliLmF1dGguYmFja2VuZHMuTW9kZWxCYWNrZW5kIiwiX2F1dGhfdXNlcl9oYXNoIjoiYzE1MTEwYTM0ZmJiMTU0NDc4MDcyYzk5NjM0MmRkOTFlMDJkODBjZSIsImlkIjo0OTEyNTg3LCJlbWFpbCI6ImhhcmRpa21pc2hyYTA1MDlAZ21haWwuY29tIiwidXNlcm5hbWUiOiJhaW1sZXNzQXJqdW4iLCJ1c2VyX3NsdWciOiJhaW1sZXNzQXJqdW4iLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvR29maW5kR29kL2F2YXRhcl8xNjMxNzE3NTQ1LnBuZyIsInJlZnJlc2hlZF9hdCI6MTY4OTU3NjIzNSwiaXAiOiIyNDA1OjIwMTozNTo5MDI0Ojg5NWM6NDdhZjpmOTk0Ojc5YWEiLCJpZGVudGl0eSI6IjE0ZDU4YTFiYTI4NmYwODdkOTczNjI0OWVjNzg1MzE0Iiwic2Vzc2lvbl9pZCI6NDI2OTk2ODYsIl9zZXNzaW9uX2V4cGlyeSI6MTIwOTYwMH0.J0zzBR9mZCppiblHSGQkcZg2tUK2VvA7zbviX5U4gG0;csrftoken:RtRYPnzpk1VPxFNUT2q88iEs3ZyjJQFuVe5REeLGVJrKfprdE1ZJFWIFMhvDy5Af;

{
    "lang": "python3",
    "question_id": "2058",
    "typed_code": "class Solution:\n    def getConcatenation(self, nums: List[int]) -> List[int]:\n        return nums + nums",
    "data_input": "[1,2,1]"
}